# we need to run it with:
#docker-compose --env-file .env.docker up --build
services:
  app:
    image: languagesgpt
    build: .
    ports:
      - "3003:3003" # Map container's React app port to host
      - "8008:8008" # Map container's JSON server port to host
    volumes:
      - "./docker_databases/languages_db.json:/app/languages_db.json" # Production database mapping
      - "./docker_databases/languages_db_dev.json:/app/languages_db_dev.json" # Development database mapping (optional if needed in container)
    env_file:
      - .env.docker
    command: "npm start"

networks:
  default:
    driver: bridge